parameters:
  foo: bar
  an_array: [1, 2, 3]

services:
  file_loader:
    # A function that will return an instance of the class we require
    # Since Common Lisp doesn't have position based class
    # constructors, a factory function is needed to map them to the class.
    factory: File-Loader-Factory
    arguments: ["../example/config_only_params.yml"]

  container_factory:
    factory: Container-Factory
    arguments: ["@file_loader"]
